export enum EVENTS_ENUM {
  CLICK = 'CLICK',
  SET_TABLE = 'SET_TABLE',
  UPDATE_ALL_CARDS = 'UPDATE_ALL_CARDS',
  REMOVE_CARD_FROM_PLAYER = 'REMOVE_CARD_FROM_PLAYER',
  DEBUG_SAVE = 'DEBUG_SAVE',
  GAME_UPDATED = 'GAME_UPDATED',
  PLAYER_TOOK = 'PLAYER_TOOK',
  TEST = 'TEST'
};

export const EVENTS = {
  [EVENTS_ENUM.CLICK]: EVENTS_ENUM.CLICK,
  [EVENTS_ENUM.SET_TABLE]: EVENTS_ENUM.SET_TABLE,
  [EVENTS_ENUM.TEST]: EVENTS_ENUM.TEST,
  [EVENTS_ENUM.UPDATE_ALL_CARDS]: EVENTS_ENUM.UPDATE_ALL_CARDS,
  [EVENTS_ENUM.REMOVE_CARD_FROM_PLAYER]: EVENTS_ENUM.REMOVE_CARD_FROM_PLAYER,
  [EVENTS_ENUM.DEBUG_SAVE]: EVENTS_ENUM.DEBUG_SAVE,
  [EVENTS_ENUM.GAME_UPDATED]: EVENTS_ENUM.GAME_UPDATED,
  [EVENTS_ENUM.PLAYER_TOOK]: EVENTS_ENUM.PLAYER_TOOK
};

export class EventEntity {
  static dispatch = (type: EVENTS_ENUM, data: any) => {
    const event = new CustomEvent(type, {
      detail: data
    });

    document.dispatchEvent(event);
  }
}
